export const products = [
    { id: 1, name: "ClearVue 650 Ultrasound System" },
    { id: 2, name: "ClearVue 350 Ultrasound System" },
    { id: 3, name: "EPIQ CVX Ultrasound Machine" },
    { id: 4, name: "ClearVue 850 Ultrasound System" },
    { id: 5, name: "ClearVue 550 Ultrasound system" },
    { id: 6, name: "Affiniti 30 Ultrasound System" },
    { id: 7, name: "Incisive CT" },
    { id: 8, name: "Mobile Diagnost WDR" },
    { id: 9, name: "Proxi Diagnost N90" },
    { id: 10, name: "Digital Diagnost C90" },
    { id: 11, name: "Affiniti 70" },
    { id: 12, name: "Affiniti 50" },
    { id: 13, name: "EPIQ Elite" },
    { id: 14, name: "PHILIPS PALM SIZE ULTRASOUND ON YOUR ANDROID DEVICE LUMIFY" },
    { id: 15, name: "Affiniti CVx" },
    { id: 16, name: "MR 7700" },
    { id: 17, name: "MR 5300" },
    { id: 18, name: "Azurion 5 M12" },
    { id: 19, name: "Azurion 7 M12" },
    { id: 20, name: "Azurion 7 M20" },
    { id: 21, name: "Azurion 3 M15" },
    { id: 22, name: "Azurion 7 M20 with FlexArm" },
    { id: 23, name: "Azurion 5 M20" },
    { id: 24, name: "Zenition 10" },
    { id: 25, name: "Zenition 30" },
    { id: 26, name: "Zenition 50" },
    { id: 27, name: "Zenition 70" },
    { id: 28, name: "Zenition 90" },
    { id: 29, name: "Bipap Machine" },
    { id: 30, name: "CPAP Machine" },
    { id: 31, name: "Cough Assist E70" },
    { id: 32, name: "Oxygen Concentrator" },
    { id: 33, name: "Philips Trilogy Evo (OBM) Ventilator" },
    { id: 34, name: "Philips Compact 5500 CV Ultrasound" },
  ];
  